import { useAuth } from '../../context/AuthContext';
import { useData } from '../../context/DataContext';
import { FileText, Download, Eye, FlaskConical, Image } from 'lucide-react';

export default function PatientReports() {
  const { user } = useAuth();
  const { getLabReportsByPatient, getDocumentsByPatient } = useData();

  const labReports = getLabReportsByPatient(user.id);
  const documents = getDocumentsByPatient(user.id);

  const handlePrint = (report) => {
    const printWindow = window.open('', '_blank');
    printWindow.document.write(`
      <html><head><title>Lab Report - ${report.testName}</title>
      <style>body{font-family:Arial,sans-serif;padding:40px;max-width:800px;margin:auto}
      h1{color:#047857;border-bottom:2px solid #10b981;padding-bottom:10px}
      .field{margin:10px 0}.label{font-weight:bold;color:#555}.value{color:#333}
      .status{display:inline-block;padding:4px 12px;border-radius:12px;font-size:12px}
      .completed{background:#dcfce7;color:#16a34a}.pending{background:#fef3c7;color:#d97706}</style></head>
      <body><h1>MediCare - Lab Report</h1>
      <div class="field"><span class="label">Test: </span><span class="value">${report.testName}</span></div>
      <div class="field"><span class="label">Patient: </span><span class="value">${report.patientName}</span></div>
      <div class="field"><span class="label">Doctor: </span><span class="value">${report.doctorName}</span></div>
      <div class="field"><span class="label">Date: </span><span class="value">${report.date}</span></div>
      <div class="field"><span class="label">Status: </span><span class="status ${report.status}">${report.status}</span></div>
      ${report.result ? `<div class="field"><span class="label">Result: </span><span class="value">${report.result}</span></div>` : ''}
      <hr style="margin-top:40px;border-color:#e5e7eb"><p style="text-align:center;color:#9ca3af;font-size:12px">Generated by MediCare Clinic Management System</p>
      </body></html>
    `);
    printWindow.document.close();
    printWindow.print();
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-surface-800">Reports & Documents</h1>
        <p className="text-surface-400 mt-1">View and download your medical reports</p>
      </div>

      {/* Lab Reports */}
      <div className="card">
        <div className="card-body">
          <h2 className="text-lg font-semibold text-surface-800 mb-4 flex items-center gap-2">
            <FlaskConical className="w-5 h-5 text-primary-500" /> Lab Reports
          </h2>
          {labReports.length === 0 ? (
            <div className="text-center py-8">
              <FlaskConical className="w-10 h-10 text-surface-200 mx-auto mb-2" />
              <p className="text-sm text-surface-400">No lab reports</p>
            </div>
          ) : (
            <div className="space-y-3">
              {labReports.map(report => (
                <div key={report.id} className="flex items-center gap-4 p-4 bg-surface-50 rounded-xl hover:bg-surface-100 transition-colors">
                  <div className={`w-11 h-11 rounded-xl flex items-center justify-center ${report.type === 'imaging' ? 'bg-purple-100' : 'bg-primary-100'}`}>
                    {report.type === 'imaging' ? <Image className="w-5 h-5 text-purple-500" /> : <FlaskConical className="w-5 h-5 text-primary-500" />}
                  </div>
                  <div className="flex-1 min-w-0">
                    <h3 className="font-semibold text-surface-800">{report.testName}</h3>
                    <p className="text-xs text-surface-400">{report.doctorName} · {report.date}</p>
                    {report.result && <p className="text-xs text-surface-500 mt-1 truncate">{report.result}</p>}
                  </div>
                  <span className={`badge ${report.status === 'completed' ? 'badge-success' : 'badge-warning'}`}>{report.status}</span>
                  {report.status === 'completed' && (
                    <button onClick={() => handlePrint(report)} className="btn btn-secondary btn-sm">
                      <Download className="w-3.5 h-3.5" /> Download
                    </button>
                  )}
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* Documents */}
      <div className="card">
        <div className="card-body">
          <h2 className="text-lg font-semibold text-surface-800 mb-4 flex items-center gap-2">
            <FileText className="w-5 h-5 text-primary-500" /> Medical Documents
          </h2>
          {documents.length === 0 ? (
            <div className="text-center py-8">
              <FileText className="w-10 h-10 text-surface-200 mx-auto mb-2" />
              <p className="text-sm text-surface-400">No documents uploaded</p>
            </div>
          ) : (
            <div className="grid md:grid-cols-2 gap-4">
              {documents.map(doc => (
                <div key={doc.id} className="flex items-center gap-3 p-4 bg-surface-50 rounded-xl">
                  <div className="w-10 h-10 rounded-lg bg-accent-100 flex items-center justify-center">
                    <FileText className="w-5 h-5 text-accent-500" />
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-semibold text-surface-800 truncate">{doc.name}</p>
                    <p className="text-xs text-surface-400">Uploaded by {doc.uploadedBy} · {doc.uploadDate}</p>
                  </div>
                  <button className="btn btn-secondary btn-sm"><Eye className="w-3.5 h-3.5" /></button>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
