import { useAuth } from '../../context/AuthContext';
import { useData } from '../../context/DataContext';
import { FileText, Printer } from 'lucide-react';

export default function DoctorPrescriptions() {
  const { user } = useAuth();
  const { prescriptions } = useData();
  const myPrescriptions = prescriptions.filter(p => p.doctorId === user.id);

  const handlePrint = (rx) => {
    const medsHtml = rx.medicines.map(m => `<tr><td style="padding:8px;border:1px solid #e5e7eb">${m.name}</td><td style="padding:8px;border:1px solid #e5e7eb">${m.dosage}</td><td style="padding:8px;border:1px solid #e5e7eb">${m.frequency}</td><td style="padding:8px;border:1px solid #e5e7eb">${m.duration}</td></tr>`).join('');
    const w = window.open('', '_blank');
    w.document.write(`<html><head><title>Prescription</title><style>body{font-family:Arial,sans-serif;padding:40px;max-width:800px;margin:auto}h1{color:#047857;border-bottom:2px solid #10b981;padding-bottom:10px}table{width:100%;border-collapse:collapse;margin:16px 0}th{background:#f0fdf4;padding:8px;text-align:left;border:1px solid #e5e7eb;font-size:13px}td{font-size:13px}.footer{text-align:center;margin-top:40px;color:#9ca3af;font-size:12px}</style></head><body>
    <h1>MediCare Prescription</h1>
    <p><strong>Patient:</strong> ${rx.patientName}</p>
    <p><strong>Doctor:</strong> ${rx.doctorName}</p>
    <p><strong>Date:</strong> ${rx.date}</p>
    <p><strong>Diagnosis:</strong> ${rx.diagnosis}</p>
    <p><strong>Known Allergies:</strong> ${rx.allergies || 'None'}</p>
    <h3>Medications</h3>
    <table><thead><tr><th>Medicine</th><th>Dosage</th><th>Frequency</th><th>Duration</th></tr></thead><tbody>${medsHtml}</tbody></table>
    ${rx.notes ? `<p><strong>Notes:</strong> ${rx.notes}</p>` : ''}
    <hr><p class="footer">Generated by MediCare Clinic Management System</p></body></html>`);
    w.document.close();
    w.print();
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-surface-800">My Prescriptions</h1>
        <p className="text-surface-400 mt-1">View and print prescriptions you've written</p>
      </div>

      {myPrescriptions.length === 0 ? (
        <div className="card">
          <div className="card-body text-center py-12">
            <FileText className="w-12 h-12 text-surface-200 mx-auto mb-3" />
            <p className="text-surface-500">No prescriptions written yet</p>
          </div>
        </div>
      ) : (
        <div className="space-y-4">
          {myPrescriptions.map(rx => (
            <div key={rx.id} className="card">
              <div className="card-body">
                <div className="flex items-center justify-between mb-3">
                  <div>
                    <h3 className="font-semibold text-surface-800">{rx.patientName}</h3>
                    <p className="text-xs text-surface-400">{rx.date}</p>
                  </div>
                  <button onClick={() => handlePrint(rx)} className="btn btn-secondary btn-sm"><Printer className="w-3.5 h-3.5" /> Print</button>
                </div>
                <p className="text-sm text-surface-600 mb-3"><strong>Diagnosis:</strong> {rx.diagnosis}</p>
                <div className="table-container">
                  <table>
                    <thead><tr><th>Medicine</th><th>Dosage</th><th>Frequency</th><th>Duration</th></tr></thead>
                    <tbody>
                      {rx.medicines.map((m, i) => (
                        <tr key={i}><td className="font-medium">{m.name}</td><td>{m.dosage}</td><td>{m.frequency}</td><td>{m.duration}</td></tr>
                      ))}
                    </tbody>
                  </table>
                </div>
                {rx.notes && <p className="text-xs text-surface-500 mt-3 italic">{rx.notes}</p>}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
